# META:
#   -
#     path: '/mnt/hwfile/alpha_vl/duruoyi_share/omicaption/flux_pro_batch_Detailed.json'
#     type: 'text_image_pair'
#   -
#     path: 'path_to_subject_driven_data'
#     type: 'subject_driven'
#   -
#     path: 'path_to_editing_data'
#     type: 'editing'

META:
  -
    root: "/root/paddlejob/workspace/env_run/output/lvfeng/InternVL/data"
    path: ["prompt","prompt_pseudo", "prompt_pseudo2"]
    type: 'text_image_pair'